CREATE TABLE public.tb_url (
	id integer NOT NULL,
	code VARCHAR(20) NOT NULL,
	url TEXT NOT NULL,
	CONSTRAINT tb_url_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE public.sq_url
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;